### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by anjuls** [hyee/dbcli#1]
I tried to set the dbcli.bat with correct TNS_ADMIN and JRE path but it is failing with below error. 
Any idea what I am doing wrong here? 

```
dbcli>dbcli.bat
    --------------------------------------------------------------------------------------------------------------------------------------
    | DBCLI, type 'conn' to connect to db, or 'help' for more information. (c)2014-2015 hyee, MIT license (https://github.com/hyee/dbcli)|
    ======================================================================================================================================

Exception in thread "main" com.naef.jnlua.LuaRuntimeException: C:\Users\anjul.sahu\home\anjul.sahu\tools\dbcli\lua\input.l:8: module 'env' not f
        no field package.preload['env']
        no file 'C:\Users\anjul.sahu\home\anjul.sahu\tools\dbcli\lua\input.l'
        no file '.\env.dll'
        no file 'C:\Program Files\Java\jre1.8.0_40\bin\env.dll'
        no file 'C:\Program Files\Java\jre1.8.0_40\bin\loadall.dll'
        at com.naef.jnlua.LuaState.lua_pcall(Native Method)
        at com.naef.jnlua.LuaState.call(Unknown Source)
        at org.dbcli.Loader.loadLua(Loader.java:82)
        at org.dbcli.Loader.main(Loader.java:122)
```

**Comment by hyee** [comment]
The directory is too deep, it doesn't support the path which exceeds 45 chars.
I've updated the code to fix your issue but still cannot support the deeper path, you may download the update or move the folder to a shorter directory.

Below the quick use of this software:
1.  "conn" or "connect" command to connect to database, it can connect to db without installing Oracle client. And "login" command to login to the account without password which has been successfully connected before. 
2.  Supports query, DML, DDL which should match Oracle syntax, similar to SQL*Plus
3. "ora" command to run pre-defined scripts under the "ora" dir, and "alias" command which is similar to that of linux.
4.  "help" or "help -a" to see all available commands

**Comment by anjuls** [comment]
Thanks Hyee... It worked. I moved the installation directory to C:/ (shorter path) to fix it.
