### ISSUE TITLE
ASHCHAIN Script only works with session id

### ISSUE THREAD

**Issue by ghost** [hyee/dbcli#24]
ASHCHAIN.sql script is only working when parameter session_id is passed. It don't return ant rows if sql_id or plan_hash_value is passed.

**Comment by hyee** [comment]
I cannot reproduce the case, the possible reason could be:
* the relative ASH data is stored in `DBA_HIST_ACTIVE_SESS_HISTORY` instead of `GV$ACTIVE_SESSION_HISTORY`, if this is the case, please  use option `-dash`
* the target `SQL_ID` is not blocked by other sessions
