### ISSUE TITLE
SSH issue

### ISSUE THREAD

**Issue by anjuls** [hyee/dbcli#4]
Hi Hyee,
when connecting through SSH, i am getting below error. Any pointers?  thanks, Anjul

`java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)`

**Comment by hyee** [comment]
Hi anjuls,

I've recurred the issue by accessing Solaris server with JRE 1.8, and found the reason with this link:  http://stackoverflow.com/questions/9162249/java-ssl-exception-prime-size-must-be-a-multiple-of-64

You may override `lib\jsch-0.1.53.jar` with the version that I just uploaded and check if the issue still exists.

I will also send an email to the author of `JSch` and see if he can provide the offical fix. Thanks.

**Comment by anjuls** [comment]
Thanks Hyee, It is working on Solaris now.
