### ISSUE TITLE
something is wrong in newer version's dbcli.bat or init.cfg

### ISSUE THREAD

**Issue by anjuls** [hyee/dbcli#7]
Hi Hyee,
After setting init.cfg (JRE_HOME and TNS_ADM), dbcli.bat is throwing below error and also console.bat is not starting the program.. It is just opening the Console.exe. 

The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The system cannot find the path specified.
Press any key to continue . . .

Not sure what's wrong or changed recently.

**Comment by hyee** [comment]
Hi Anjuls,
Does the path contain white space? In this case, please enclose with quote("). Supposing target jre dir is `c:\java 1.76`, then the config should be:

```
set "JRE_HOME=c:\java 1.76"
```

And should not leave space before or after the `=` symbol
Besides, please make sure `dbcli.bat` is up to date

**Comment by anjuls** [comment]
Hi Hyee,

The problem is with Console.  I have used double quotes, still I am not getting dbcli interface in console. It just opens the console without loading DBCLI.

Not sure where the problem is ...

**Comment by hyee** [comment]
Hi Anjuls, 

Could you open dbcli.bat with text editor, go to line#37, replace `"!JRE_HOME!\java.exe"` as `java.exe`, save and retry?

**Comment by hyee** [comment]
Another possible reason is `ansicon.exe` doesn't exist in `lib\x64` or `lib\x86`, which means it may have been deleted by other program.

If you don't want to use ansicon(https://github.com/adoxa/ansicon), you can just remove line#8, which is `if not defined ANSICON_CMD SET ANSICON_CMD=.\lib\x64\ansicon.exe`

**Comment by anjuls** [comment]
I replaced it in line # 37, `dbcli.bat` is working but not `console.bat`. 

Tried commenting the ansicon, din't help. I have the `ansicon.exe` present

**Comment by hyee** [comment]
OK, for console, please try following steps until dbcli is able to use:
- Go to `bin\consolez`, start `console.exe`
- Go to `bin\consolez`, replace `console.xml` as this project's version, and goto `%APPDATA%\console` directory(normally as `C:\Users\<yourname>\AppData\Roaming\console`), check if `console.xml` exists, if yes then delete it. Then go back to `bin\consolez` and run  `console.exe`
- Go to `bin\consolez`, delete `console.xml`, start `console.exe`, go to edit->settings->tabs, in the `shell` field, fill with the path of `dbcli.bat`. i.e., `c:\soft\dbcli\dbcli.bat`. Save and open new tab

**Comment by anjuls** [comment]
2nd step fixed it, 

_Solution_: Removed console.xml from my Roaming\console directory.

Thanks Hyee.
