### ISSUE TITLE
Connection alias missing? 

### ISSUE THREAD

**Issue by alaahong** [hyee/dbcli#8]
There was one error while I first type in "login" after computer started.

```
SQL> login 1
No available logins for '1' in group 'oracle'. 
SQL> login
No available logins for '' in group 'oracle'.
SQL> login ae
No available logins for 'ae' in group 'oracle'.
```

I need re-input the connection, and they are all missing which I stored before.

Is it an existing issue?

First type:
[Issue](https://github.com/alaahong/storage/blob/master/dbcli.png)
Login list is back to normal after I create conn again.
[Normal](https://github.com/alaahong/storage/blob/master/360%E6%88%AA%E5%9B%BE-1339908.png)

**Comment by hyee** [comment]
Reason is file "password.dat" under sub-folder "data" is missing after you rebooted your PC, please check wether it was deleted by other sowftware.

**Comment by alaahong** [comment]
Hi,
You're right. Seems cause by I open dbcli in another path, so there was not the previous password.dat. 

Thanks~
